// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAFlkMfWpA8tpeKZip78uLa8GblPxsYE8',
    appId: '1:162898325465:web:5e474c9d3436b7203ff3c8',
    messagingSenderId: '162898325465',
    projectId: 'sorun-bildirme-uygulamasi',
    authDomain: 'sorun-bildirme-uygulamasi.firebaseapp.com',
    storageBucket: 'sorun-bildirme-uygulamasi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWdQ-fYTqv9QODuIZaFFACmeUVpU6gKfs',
    appId: '1:162898325465:android:a2160e22ab992dcb3ff3c8',
    messagingSenderId: '162898325465',
    projectId: 'sorun-bildirme-uygulamasi',
    storageBucket: 'sorun-bildirme-uygulamasi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUY44I3bBpVTTR4kH_tdfMrocwZ00dmZM',
    appId: '1:162898325465:ios:54003229b8cbe9443ff3c8',
    messagingSenderId: '162898325465',
    projectId: 'sorun-bildirme-uygulamasi',
    storageBucket: 'sorun-bildirme-uygulamasi.appspot.com',
    iosBundleId: 'com.example.sorunBildirimUygulamasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUY44I3bBpVTTR4kH_tdfMrocwZ00dmZM',
    appId: '1:162898325465:ios:90b8168b72718f873ff3c8',
    messagingSenderId: '162898325465',
    projectId: 'sorun-bildirme-uygulamasi',
    storageBucket: 'sorun-bildirme-uygulamasi.appspot.com',
    iosBundleId: 'com.example.sorunBildirimUygulamasi.RunnerTests',
  );
}
